services:
  api-1:
    image: ghcr.io/williancesar/rinha-fraud-api:v20260504-220528-95b19c4
    deploy:
      resources:
        limits:
          cpus: "0.425"
          memory: "151M"
    networks: [rinha]

  api-2:
    image: ghcr.io/williancesar/rinha-fraud-api:v20260504-220528-95b19c4
    deploy:
      resources:
        limits:
          cpus: "0.425"
          memory: "151M"
    networks: [rinha]

  lb:
    image: haproxy:3.0-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "48M"
    depends_on:
      - api-1
      - api-2
    networks: [rinha]

networks:
  rinha:
    driver: bridge
